Update biography DEFAULTSORT autofill to work with paranthetical disambiguation
wikimedia-gadgets/afc-helper pull request #225
Opened 2022-04-22 01:15 UTC by kzhovn

Very small PR just to make sure I understand how everything works before I try to handle any of the outstanding issues: when accepting a biography, autofills name when there is a parenthetical disambiguation and otherwise the title looks to be Firstname Lastname. (Also, my IDE took umbrage with package.json's testMatch having two entries on one line and decided to fix it for me, which I haven't undone because it seems like a reasonable formatting change. Happy to undo it if that's a problem.)

![Screenshot from 2022-04-21 21-07-26](https://user-images.githubusercontent.com/60860948/164576857-79d76ce7-d5a5-4681-a657-803ed4318ed9.png)

2022-07-27 06:52 UTC, siddharthvp requested changes
sorry for the late review :D

2022-07-27 06:52 UTC, siddharthvp commented on src/modules/submissions.js
> +					// after removing any trailing parantheticals (likely disambiguation), and
typo: parentheticals

2022-07-27 06:52 UTC, siddharthvp commented on src/modules/submissions.js
> +					title = afchSubmission.shortTitle.replace(/ \([\s\S]*?\)$/g, '')
`var` keyword is missing

2022-07-27 06:52 UTC, siddharthvp commented on src/modules/submissions.js
> +					title = afchSubmission.shortTitle.replace(/ \([\s\S]*?\)$/g, '')
Please run `eslint --fix .`. Style convention in this project is to haves spaces before opening and closing parentheses.

2024-04-09 13:14 UTC, NovemLinguae commented
This patch fixes bad first name last name suggestions for articles with parentheses at the end. Old:

<img width="532" alt="image" src="https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/07655a82-da35-4ffb-b0a4-3b1e986610c9">

New:

blank (which is good, can't tell if one word is a first name or a last name)

Sorry this took two years. Approved. Thanks for the patch!

2024-04-09 13:14 UTC, merged